title: Zeel Bhatt
description: Computer Vision, Structure from motion
theme: jekyll-theme-minimal

# About Me

I am a passionate web developer with a love for coding and design. I have a strong background in...

## Education

- Bachelor's Degree in Computer Science, XYZ University (Year)
- ...

## Interests

- Web Development
- Frontend Technologies

